---
# tasks file for sbt
- name: add SBT debian repository
  shell: |
      echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
      apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823

- name: install SBT
  apt: name=sbt state=present update_cache=yes
